server:
  port: 8080

spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/likedemo
    username: user
    password: password

  data:
    redis:
      repositories:
        enabled: false
      host: localhost
      port: 6379
  jpa:
    open-in-view: false
    properties:
      hibernate.log_slow_query: 1000
      hibernate.highlight_sql: true
      jakarta.persistence.schema-generation.database.action: update

logging:
  level:
    com.jhh: trace
    org.hibernate.SQL_SLOW: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace